version: '3.9'
services:
  db:
    image: postgres:13.3
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nextjs-prisma-graphql-codegen-sample
  prisma-migrate:
    build:
      context: prisma
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/nextjs-prisma-graphql-codegen-sample?schema=public
    depends_on:
      - db
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
volumes:
  postgres:
